---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/data/blogPosts
  label: Blog Posts
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
upload_dir: public/media
public_path: "/public/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
