backend:
  name: test-repo #git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
